version: '3.8'

services:
  nextjs-app:
    volumes:
      - .:/app              # Mount your local project into the container
      - /app/node_modules   # Prevent local node_modules overwrite
    environment:
      - NODE_ENV=development
    command: npm run dev    # Run in development mode
